// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdDTxLwETzvQkLxjdi-NLvzWd__Z-Scr8',
    appId: '1:47887754647:web:5d73f75660cef0c067d0d2',
    messagingSenderId: '47887754647',
    projectId: 'blood-e4542',
    authDomain: 'blood-e4542.firebaseapp.com',
    storageBucket: 'blood-e4542.appspot.com',
    measurementId: 'G-GC2FSLE4GB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLuW_OU29vOHtHLKww5tjd7bCLt7iwkeo',
    appId: '1:47887754647:android:31cac9d9b9187eb167d0d2',
    messagingSenderId: '47887754647',
    projectId: 'blood-e4542',
    storageBucket: 'blood-e4542.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCyPSa57J9C2fpD0Uk4rEbEsEBnuXqJHQ',
    appId: '1:47887754647:ios:d9323b3463643eac67d0d2',
    messagingSenderId: '47887754647',
    projectId: 'blood-e4542',
    storageBucket: 'blood-e4542.appspot.com',
    iosBundleId: 'com.example.bloodDonationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCyPSa57J9C2fpD0Uk4rEbEsEBnuXqJHQ',
    appId: '1:47887754647:ios:3d7a15521315b69167d0d2',
    messagingSenderId: '47887754647',
    projectId: 'blood-e4542',
    storageBucket: 'blood-e4542.appspot.com',
    iosBundleId: 'com.example.bloodDonationApp.RunnerTests',
  );
}
